apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordenes-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ordenes-service
  template:
    metadata:
      labels:
        app: ordenes-service
    spec:
      containers:
        - name: ordenes-service
          image: ordenes-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3003
          env:
            - name: PORT
              value: "3003"
