apiVersion: apps/v1
kind: Deployment
metadata:
  name: productos-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: productos-service
  template:
    metadata:
      labels:
        app: productos-service
    spec:
      containers:
        - name: productos-service
          image: productos-service
          imagePullPolicy: IfNotPresent 
          ports:
            - containerPort: 3002
          volumeMounts:
                      - name: sqlite-storage
                        mountPath: "/app/src/database.db"
      volumes:
                  - name: sqlite-storage
                    persistentVolumeClaim:
                      claimName: sqlite-pvc