apiVersion: apps/v1
kind: Deployment
metadata:
  name: usuarios-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: usuarios-service
  template:
    metadata:
      labels:
        app: usuarios-service
    spec:
      containers:
        - name: usuarios-service
          image: usuarios-service:latest  # Cambia esto si subes la imagen a Docker Hub
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
