apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolithic-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monolithic
  template:
    metadata:
      labels:
        app: monolithic
    spec:
      containers:
        - name: monolithic
          image: localhost:5000/monolitico-app 
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "monolithic-db"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "password"
            - name: DB_NAME
              value: "monolith"
