version: "3.8"

services:
  ordenes-service:
    build: ./ordenes-service
    ports:
      - "3000:3000"
    depends_on:
      - productos-service
      - usuarios-service

  productos-service:
    build: ./productos-service
    ports:
      - "3002:3002"

  usuarios-service:
    build: ./usuarios-service
    ports:
      - "3001:3001"
